tap "cjbassi/ytop"
tap "clementtsang/bottom"
tap "d12frosted/emacs-plus"
tap "hashicorp/tap"
tap "holoarchivists/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "homebrew/test-bot"
tap "oven-sh/bun"
tap "platogo/tap", "https://github.com/platogo/homebrew-tap.git"
tap "pulumi/tap"
tap "supabase/tap"
tap "superfly/tap"
tap "unused-code/formulae"
brew "act"
cask "anki"
cask "arc"
cask "avifquicklook"
cask "blender"
cask "chatgpt"
cask "chromedriver"
cask "deepl"
cask "figma"
cask "font-fira-code"
cask "google-drive"
cask "handbrake"
cask "karabiner-elements"
cask "keycastr"
cask "logitech-options"
cask "mitmproxy"
cask "obs"
cask "orbstack"
cask "paintbrush"
cask "sketch"
cask "sourcetree"
cask "transmission"
cask "transmission-remote-gui"
cask "visual-studio-code"
cask "vlc"
cask "vnc-viewer"
cask "whisky"
cask "wireshark"
cask "xbar"
cask "xquartz"
mas "Affinity Photo", id: 824183456
mas "Amphetamine", id: 937984704
mas "Balance Lock", id: 1019371109
mas "Boop", id: 1518425043
mas "CapCut", id: 1500855883
mas "Clocker", id: 1056643111
mas "Congress", id: 1488917782
mas "Developer", id: 640199958
mas "Equinox", id: 1591510203
mas "Furiganify!", id: 1151320968
mas "ImageTextOCR", id: 1495787023
mas "JSONPeep", id: 1458969831
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Notion Web Clipper", id: 1559269364
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Prime Video", id: 545519333
mas "Quick Camera", id: 598853070
mas "Saber", id: 1671523739
mas "Session", id: 1521432881
mas "Shazam", id: 897118787
mas "Slack", id: 803453959
mas "Speediness", id: 1596706466
mas "Telegram", id: 747648890
mas "TestFlight", id: 899247664
mas "Vimari", id: 1480933944
mas "Xcode", id: 497799835
mas "‎WhatsApp", id: 310633997
vscode "akamud.vscode-theme-onedark"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "asciidoctor.asciidoctor-vscode"
vscode "astro-build.astro-vscode"
vscode "aykutsarac.jsoncrack-vscode"
vscode "ban.spellright"
vscode "betterthantomorrow.calva"
vscode "betterthantomorrow.calva-spritz"
vscode "bierner.markdown-mermaid"
vscode "bradlc.vscode-tailwindcss"
vscode "brettm12345.nixfmt-vscode"
vscode "budparr.language-hugo-vscode"
vscode "caarlos0.language-prometheus"
vscode "castwide.solargraph"
vscode "cesium.gltf-vscode"
vscode "codescene.codescene-vscode"
vscode "cssho.vscode-svgviewer"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "deepinthought.vscode-shell-snippets"
vscode "deerawan.vscode-dash"
vscode "denoland.vscode-deno"
vscode "donjayamanne.python-environment-manager"
vscode "donjayamanne.python-extension-pack"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "editorconfig.editorconfig"
vscode "erlang-ls.erlang-ls"
vscode "esbenp.prettier-vscode"
vscode "figma.figma-vscode-extension"
vscode "florinpatrascu.vscode-elixir-snippets"
vscode "formulahendry.code-runner"
vscode "formulahendry.github-actions"
vscode "foxundermoon.shell-format"
vscode "fumobox.vtool"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-execution"
vscode "graphql.vscode-graphql-syntax"
vscode "hashicorp.terraform"
vscode "hridoy.rails-snippets"
vscode "idered.npm"
vscode "idleberg.applescript"
vscode "ing-bank.vscode-psl"
vscode "janisdd.vscode-edit-csv"
vscode "jebbs.plantuml"
vscode "jnoortheen.nix-ide"
vscode "jolaleye.horizon-theme-vscode"
vscode "josetr.cmake-language-support-vscode"
vscode "kahole.magit"
vscode "karunamurti.haml"
vscode "katsute.code-background"
vscode "kevinrose.vsc-python-indent"
vscode "koichisasada.vscode-rdbg"
vscode "leonardssh.vscord"
vscode "lexical-lsp.lexical"
vscode "llvm-vs-code-extensions.vscode-clangd"
vscode "lokalise.i18n-ally"
vscode "luquedaniel.languague-renpy"
vscode "marp-team.marp-vscode"
vscode "mattn.lisp"
vscode "mechatroner.rainbow-csv"
vscode "mgmcdermott.vscode-language-babel"
vscode "mindaro-dev.file-downloader"
vscode "mindaro.mindaro"
vscode "misogi.ruby-rubocop"
vscode "mkhl.direnv"
vscode "mlueckert.a-frame-completion"
vscode "mrmlnc.vscode-csscomb"
vscode "mrorz.language-gettext"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-playwright.playwright"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.hexeditor"
vscode "ms-vscode.live-server"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "mtxr.sqltools"
vscode "mtxr.sqltools-driver-pg"
vscode "naumovs.color-highlight"
vscode "njpwerner.autodocstring"
vscode "noku.rails-run-spec-vscode"
vscode "orta.vscode-jest"
vscode "pantajoe.vscode-elixir-credo"
vscode "pgourlain.erlang"
vscode "phoenixframework.phoenix"
vscode "pkief.material-icon-theme"
vscode "pomdtr.excalidraw-editor"
vscode "randomfractalsinc.vscode-vega-viewer"
vscode "redhat.java"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "remisa.shellman"
vscode "ricard.postcss"
vscode "samuelcolvin.jinjahtml"
vscode "saratravi.elixir-formatter"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "shopify.ruby-extensions-pack"
vscode "shopify.ruby-lsp"
vscode "sidthesloth.html5-boilerplate"
vscode "smockle.xcode-default-theme"
vscode "sorbet.sorbet-vscode-extension"
vscode "steoates.autoimport"
vscode "stevencl.adddoccomments"
vscode "sumneko.lua"
vscode "svelte.svelte-vscode"
vscode "tamasfe.even-better-toml"
vscode "techer.open-in-browser"
vscode "technosophos.vscode-make"
vscode "terrastruct.d2"
vscode "tootone.org-mode"
vscode "twxs.cmake"
vscode "uetchy.ancient-one-dark"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vitest.explorer"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscodevim.vim"
vscode "vsls-contrib.gistfs"
vscode "vtrois.gitmoji-vscode"
vscode "wakatime.vscode-wakatime"
vscode "wayou.vscode-todo-highlight"
vscode "wholroyd.jinja"
vscode "william-voyek.vscode-nginx"
vscode "xabikos.javascriptsnippets"
vscode "yoavbls.pretty-ts-errors"
vscode "yzhang.markdown-all-in-one"
vscode "zignd.html-css-class-completion"
vscode "zxh404.vscode-proto3"
